acl SSL_ports port 443
acl CONNECT method CONNECT
acl approved_tls dstdomain api.codestra.co auth.codestra.co

http_access deny !CONNECT
http_access deny !SSL_ports
http_access allow CONNECT approved_tls
http_access deny all

http_port 3128
request_header_access Authorization allow all
access_log stdio:/dev/stdout
